### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by derjoern** [mark-me/Pi-Jukebox#2]
It would be nice when your software would have a configurable blank screen option. An always on display is rather distracting at night.

**Comment by GlodNet** [comment]
My intention is to build my Pi into a sort of "Internet Radio" even going as far as having it battery powered.  The lack of a power-off or sleep mode is something that I was intending to discuss with Mark, wherever he's got to.

**Comment by zalun** [comment]
sleep mode is definitely something to put there. This would however require either a separate "wakeup" button or making it wake up from touching the screen (preferable). 
Making it to sleep is a part of this repo, but waking up should be done by raspberry pi.

**Comment by GlodNet** [comment]
> Making it to sleep is a part of this repo

Unfortunately, PiJ crashes rather a lot on my RPi.  I've no idea if this is software or hardware related.  In either case, if PiJ crashes then the only way I have of shutting down or rebooting is to SSH into the RPi.  Hence, my favoured approach is to add a _seperate_ daemon that monitors a GPIO pin in order to implement a "shutdown button".

However, I have an interference problem that I have to get rid of before boxing the system up...  (I get computer "busy" noises on the RPi's audio output.  Powering via the GPIO header improves this but doesn't _eliminate_ the problem completely.)

**Comment by mark-me** [comment]
Hi there... After waking up after a really long time, I revived the project. The blank screen is something I will definitely work on in the coming days. Thanks for the suggestion!

**Comment by mark-me** [comment]
I hope I nailed it. The blank screen activates at 10 minutes now. If you want to change that, edit the value of the BLANK_PERIOD in gui_screens.py. I will add changing it in the settings later.
