### ISSUE TITLE
Feature Request: Karaoke/Lyrics display

### ISSUE THREAD

**Issue by phedders** [mark-me/Pi-Jukebox#4]
I'm thinking of building a portable jukebox for my kids - and adding a mic or two so they can sing along - This code looks awesome and just the ticket. Many thanks!

It would be great if lyrics could be shown on the screen if they are available.

Any thoughts or suggestions about how/where to start adding code? (I'm not yet a pythonista....)

**Comment by mark-me** [comment]
Hi there! I'm not planning to add karaoke support, since I would not want this myself. I suggest adding code to the screen_player screen. But more probably you'd want to add your own screen, which is not that difficult to do.

How you will get the lyrics in there is something I have no real clue about. You will download them from the internet? And timing wise? I will be curious to see how you go about doing this! :-)
